# Task - 1) Prepare a classification model using Naive Bayes for salary data 

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [3]:
train_df = pd.read_csv('data/SalaryData_Train.csv')
test_df = pd.read_csv('data/SalaryData_Test.csv')

In [4]:
train_df.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [5]:
test_df.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [6]:
print(train_df.shape , '\n',test_df.shape)

(30161, 14) 
 (15060, 14)


In [7]:
train_df.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [8]:
test_df.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [10]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [11]:
train_df2 = pd.get_dummies(train_df , drop_first= True)
test_df2 = pd.get_dummies(test_df , drop_first= True)

In [12]:
train_df2.head()

age  educationno  capitalgain  capitalloss  hoursperweek  \
0   39           13         2174            0            40   
1   50           13            0            0            13   
2   38            9            0            0            40   
3   53            7            0            0            40   
4   28           13            0            0            40   

   workclass_ Local-gov  workclass_ Private  workclass_ Self-emp-inc  \
0                     0                   0                        0   
1                     0                   0                        0   
2                     0                   1                        0   
3                     0                   1                        0   
4                     0                   1                        0   

   workclass_ Self-emp-not-inc  workclass_ State-gov  ...  \
0                            0                     1  ...   
1                            1                     0  ...   
2                            0                     0  ...   
3                            0                     0  ...   
4                            0                     0  ...   

   native_ Puerto-Rico  native_ Scotland  native_ South  native_ Taiwan  \
0                    0                 0              0               0   
1                    0                 0              0               0   
2                    0                 0              0               0   
3                    0                 0              0               0   
4                    0                 0              0               0   

   native_ Thailand  native_ Trinadad&Tobago  native_ United-States  \
0                 0                        0                      1   
1                 0                        0                      1   
2                 0                        0                      1   
3                 0                        0                      1   
4                 0                        0                      0   

   native_ Vietnam  native_ Yugoslavia  Salary_ >50K  
0                0                   0             0  
1                0                   0             0  
2                0                   0             0  
3                0                   0             0  
4                0                   0             0  

[5 rows x 95 columns]

In [18]:
# Normalization function 
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [21]:
train_df_norm = norm_func(train_df2.iloc[:,:])
test_df_norm = norm_func(test_df2.iloc[:,:])

In [22]:
# Separating target column
x_train = train_df2.iloc[:,:-1]
y_train = train_df2.iloc[:,-1]
x_test = test_df2.iloc[:,:-1]
y_test = test_df2.iloc[:,-1]

# Applying Naive Bayes models

## 1. Gaussian NB

In [23]:
gnb = GaussianNB()

In [24]:
gnb.fit(x_train , y_train)
y_pred = gnb.predict(x_test)

In [29]:
# Performance
print('Predicted value counts: \n',pd.Series(y_pred).value_counts())
print('-'*50)
print('Confusion Matrix: \n', confusion_matrix(y_test , y_pred))
print('-'*50) 
print('Classification Report: \n', classification_report(y_test , y_pred))
print('-'*50)
print('Accuracy Score = ',accuracy_score(y_test , y_pred))

Predicted value counts: 
 0    10692
1     4368
dtype: int64
--------------------------------------------------
Confusion Matrix: 
 [[9685 1675]
 [1007 2693]]
--------------------------------------------------
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.85      0.88     11360
           1       0.62      0.73      0.67      3700

    accuracy                           0.82     15060
   macro avg       0.76      0.79      0.77     15060
weighted avg       0.83      0.82      0.83     15060

--------------------------------------------------
Accuracy Score =  0.8219123505976096


## 2. Multinomial NB

In [30]:
mnb = MultinomialNB()

In [31]:
mnb.fit(x_train,y_train)

MultinomialNB()

In [32]:
y_pred = mnb.predict(x_test)

In [33]:
# Performance
print('Predicted value counts: \n',pd.Series(y_pred).value_counts())
print('-'*50)
print('Confusion Matrix: \n', confusion_matrix(y_test , y_pred))
print('-'*50) 
print('Classification Report: \n', classification_report(y_test , y_pred))
print('-'*50)
print('Accuracy Score = ',accuracy_score(y_test , y_pred))

Predicted value counts: 
 0    13811
1     1249
dtype: int64
--------------------------------------------------
Confusion Matrix: 
 [[10891   469]
 [ 2920   780]]
--------------------------------------------------
Classification Report: 
               precision    recall  f1-score   support

           0       0.79      0.96      0.87     11360
           1       0.62      0.21      0.32      3700

    accuracy                           0.77     15060
   macro avg       0.71      0.58      0.59     15060
weighted avg       0.75      0.77      0.73     15060

--------------------------------------------------
Accuracy Score =  0.7749667994687915


## 3. Bernoulli NB

In [34]:
bnb = BernoulliNB()

In [35]:
bnb.fit(x_train , y_train)

BernoulliNB()

In [36]:
y_pred = bnb.predict(x_test)

In [37]:
# Performance
print('Predicted value counts: \n',pd.Series(y_pred).value_counts())
print('-'*50)
print('Confusion Matrix: \n', confusion_matrix(y_test , y_pred))
print('-'*50) 
print('Classification Report: \n', classification_report(y_test , y_pred))
print('-'*50)
print('Accuracy Score = ',accuracy_score(y_test , y_pred))

Predicted value counts: 
 0    10243
1     4817
dtype: int64
--------------------------------------------------
Confusion Matrix: 
 [[9311 2049]
 [ 932 2768]]
--------------------------------------------------
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.82      0.86     11360
           1       0.57      0.75      0.65      3700

    accuracy                           0.80     15060
   macro avg       0.74      0.78      0.76     15060
weighted avg       0.83      0.80      0.81     15060

--------------------------------------------------
Accuracy Score =  0.802058432934927


### Gaussian NB performed the best for this dataset followed by Bernoulli NB and finally Multinomial NB